import { revalidateLogic } from "@tanstack/react-form"
import { useServerFn } from "@tanstack/react-start"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { CloseCircle } from "@solar-icons/react"
import type { ReactElement } from "react"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { cancelPurchaseQuotation } from "@/features/purchase-quotations/api/server-functions/cancel-purchase-quotation.api"
import { cancelPurchaseQuotationSchema } from "@/features/purchase-quotations/schemas/cancel-purchase-quotation.schema"
import { useAppForm } from "@/hooks/use-app-form"
import type { PurchaseQuotationDetail } from "@/lib/types/purchase-quotation.type"

type CancelQuotationDialogProps = {
  purchaseQuotation: PurchaseQuotationDetail
  trigger: ReactElement
}

// APPROVED → CANCELLED (terminal), reason required. Backend deletes the pending purchase orders
// generated by this RFQ and releases its quoted quantities back to the purchase request; blocked
// (order_already_placed) if any order was already placed. Dialog (not AlertDialog) for the reason field.
export function CancelQuotationDialog({
  purchaseQuotation,
  trigger,
}: CancelQuotationDialogProps) {
  const [open, setOpen] = useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger render={trigger} />
      <DialogContent className="sm:max-w-md">
        {/* The dialog unmounts content while closed, so the form (and its mutation state)
            re-mounts fresh each time the dialog opens. */}
        <CancelQuotationForm
          purchaseQuotation={purchaseQuotation}
          onClose={() => setOpen(false)}
        />
      </DialogContent>
    </Dialog>
  )
}

type CancelQuotationFormProps = {
  purchaseQuotation: PurchaseQuotationDetail
  onClose: () => void
}

function CancelQuotationForm({
  purchaseQuotation,
  onClose,
}: CancelQuotationFormProps) {
  const queryClient = useQueryClient()
  const cancelPurchaseQuotationFn = useServerFn(cancelPurchaseQuotation)

  const mutation = useMutation({
    mutationFn: (reason: string) =>
      cancelPurchaseQuotationFn({
        data: { purchaseQuotationId: purchaseQuotation.id, reason },
      }),
    onSuccess: async () => {
      onClose()
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["purchase-quotations"] }),
        queryClient.invalidateQueries({ queryKey: ["purchase-orders"] }),
        queryClient.invalidateQueries({ queryKey: ["purchase-requests"] }),
        queryClient.invalidateQueries({ queryKey: ["purchase-ledger"] }),
        queryClient.invalidateQueries({ queryKey: ["reports"] }),
      ])
    },
  })

  const form = useAppForm({
    defaultValues: { reason: "" },
    validationLogic: revalidateLogic(),
    validators: {
      onDynamic: cancelPurchaseQuotationSchema.pick({ reason: true }),
    },
    onSubmit: ({ value }) => mutation.mutate(value.reason),
  })

  return (
    <form
      onSubmit={(event) => {
        event.preventDefault()
        event.stopPropagation()
        if (form.state.isSubmitting) return
        form.handleSubmit()
      }}
      noValidate
      className="flex flex-col gap-5"
    >
      <DialogHeader className="gap-1">
        <DialogTitle className="flex items-center gap-2 text-base font-semibold">
          <CloseCircle className="size-4 text-destructive" />
          Hủy báo giá {purchaseQuotation.code}
        </DialogTitle>
        <DialogDescription className="text-xs leading-normal">
          Báo giá sẽ chuyển sang "Đã hủy" và các đơn mua chờ xác nhận đã tạo từ
          báo giá này sẽ bị xóa. Số lượng đã báo giá được trả lại để đề xuất mua
          hàng báo giá lại. Không thể hoàn tác.
        </DialogDescription>
      </DialogHeader>

      <form.AppField name="reason">
        {(field) => (
          <field.TextareaField
            label="Lý do hủy"
            required
            placeholder="Ví dụ: Không mua nữa, NCC ngừng cung cấp"
          />
        )}
      </form.AppField>

      {mutation.error ? (
        <p className="text-sm text-destructive">{mutation.error.message}</p>
      ) : null}

      <DialogFooter className="gap-2">
        <Button
          type="button"
          variant="outline"
          onClick={onClose}
          disabled={mutation.isPending}
        >
          Hủy
        </Button>
        <Button
          type="submit"
          variant="destructive"
          disabled={mutation.isPending}
        >
          {mutation.isPending ? "Đang xử lý..." : "Hủy báo giá"}
        </Button>
      </DialogFooter>
    </form>
  )
}
