import { useServerFn } from "@tanstack/react-start"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { Restart } from "@solar-icons/react"
import type { ReactNode } from "react"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import { recallPurchaseQuotation } from "@/features/purchase-quotations/api/server-functions/recall-purchase-quotation.api"
import type { PurchaseQuotationDetail } from "@/lib/types/purchase-quotation.type"

type RecallQuotationDialogProps = {
  detail: PurchaseQuotationDetail
  trigger: ReactNode
}

// APPROVED → DRAFT. Backend keeps approvedBy/approvedAt as history, clears every winning NCC
// selection, and hard-deletes the DRAFT purchase orders generated by this quotation — blocked
// (purchase_quotation.error.order_already_placed) if any of them was already placed.
export function RecallQuotationDialog({
  detail,
  trigger,
}: RecallQuotationDialogProps) {
  const [open, setOpen] = useState(false)
  const queryClient = useQueryClient()
  const recallPurchaseQuotationFn = useServerFn(recallPurchaseQuotation)

  const mutation = useMutation({
    mutationFn: () =>
      recallPurchaseQuotationFn({
        data: { purchaseQuotationId: detail.id },
      }),
    onSuccess: async () => {
      setOpen(false)
      await queryClient.invalidateQueries({
        queryKey: ["purchase-quotations"],
      })
      await queryClient.invalidateQueries({
        queryKey: ["purchase-orders"],
      })
    },
  })

  return (
    <AlertDialog
      open={open}
      onOpenChange={(next) => {
        setOpen(next)
        if (next) mutation.reset()
      }}
    >
      <AlertDialogTrigger asChild>{trigger}</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogMedia>
            <Restart />
          </AlertDialogMedia>
          <AlertDialogTitle>Thu hồi báo giá này về nháp?</AlertDialogTitle>
          <AlertDialogDescription>
            {`Báo giá ${detail.code} sẽ chuyển về "Nháp". Các đơn mua nháp đã tạo từ báo giá này sẽ bị xóa.`}
          </AlertDialogDescription>
        </AlertDialogHeader>

        {mutation.error ? (
          <p className="text-sm text-destructive">{mutation.error.message}</p>
        ) : null}

        <AlertDialogFooter>
          <AlertDialogCancel disabled={mutation.isPending}>
            Hủy
          </AlertDialogCancel>
          <AlertDialogAction
            disabled={mutation.isPending}
            onClick={(event) => {
              event.preventDefault()
              mutation.mutate()
            }}
          >
            {mutation.isPending ? "Đang xử lý..." : "Thu hồi"}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
