/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedManageRouteImport } from './routes/(authed)/manage'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authedManageUsersRouteImport } from './routes/(authed)/manage_/users'
import { Route as authedManageProductsRouteImport } from './routes/(authed)/manage_/products'
import { Route as authedManageUsersCreateRouteImport } from './routes/(authed)/manage_/users_/create'
import { Route as authedManageUsersUserIdEditRouteImport } from './routes/(authed)/manage_/users_/$userId.edit'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedManageRoute = authedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => authedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authedManageUsersRoute = authedManageUsersRouteImport.update({
  id: '/manage_/users',
  path: '/manage/users',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageProductsRoute = authedManageProductsRouteImport.update({
  id: '/manage_/products',
  path: '/manage/products',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageUsersCreateRoute = authedManageUsersCreateRouteImport.update({
  id: '/manage_/users_/create',
  path: '/manage/users/create',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageUsersUserIdEditRoute =
  authedManageUsersUserIdEditRouteImport.update({
    id: '/manage_/users_/$userId/edit',
    path: '/manage/users/$userId/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/manage': typeof authedManageRoute
  '/manage/products': typeof authedManageProductsRoute
  '/manage/users': typeof authedManageUsersRoute
  '/manage/users/create': typeof authedManageUsersCreateRoute
  '/manage/users/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/manage': typeof authedManageRoute
  '/manage/products': typeof authedManageProductsRoute
  '/manage/users': typeof authedManageUsersRoute
  '/manage/users/create': typeof authedManageUsersCreateRoute
  '/manage/users/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(authed)/manage': typeof authedManageRoute
  '/(authed)/manage_/products': typeof authedManageProductsRoute
  '/(authed)/manage_/users': typeof authedManageUsersRoute
  '/(authed)/manage_/users_/create': typeof authedManageUsersCreateRoute
  '/(authed)/manage_/users_/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage'
    | '/manage/products'
    | '/manage/users'
    | '/manage/users/create'
    | '/manage/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manage'
    | '/manage/products'
    | '/manage/users'
    | '/manage/users/create'
    | '/manage/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authed)'
    | '/(auth)/login'
    | '/(authed)/manage'
    | '/(authed)/manage_/products'
    | '/(authed)/manage_/users'
    | '/(authed)/manage_/users_/create'
    | '/(authed)/manage_/users_/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/manage': {
      id: '/(authed)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof authedManageRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authed)/manage_/users': {
      id: '/(authed)/manage_/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof authedManageUsersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/products': {
      id: '/(authed)/manage_/products'
      path: '/manage/products'
      fullPath: '/manage/products'
      preLoaderRoute: typeof authedManageProductsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/users_/create': {
      id: '/(authed)/manage_/users_/create'
      path: '/manage/users/create'
      fullPath: '/manage/users/create'
      preLoaderRoute: typeof authedManageUsersCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/users_/$userId/edit': {
      id: '/(authed)/manage_/users_/$userId/edit'
      path: '/manage/users/$userId/edit'
      fullPath: '/manage/users/$userId/edit'
      preLoaderRoute: typeof authedManageUsersUserIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedManageRoute: typeof authedManageRoute
  authedManageProductsRoute: typeof authedManageProductsRoute
  authedManageUsersRoute: typeof authedManageUsersRoute
  authedManageUsersCreateRoute: typeof authedManageUsersCreateRoute
  authedManageUsersUserIdEditRoute: typeof authedManageUsersUserIdEditRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedManageRoute: authedManageRoute,
  authedManageProductsRoute: authedManageProductsRoute,
  authedManageUsersRoute: authedManageUsersRoute,
  authedManageUsersCreateRoute: authedManageUsersCreateRoute,
  authedManageUsersUserIdEditRoute: authedManageUsersUserIdEditRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
