/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedManageRouteImport } from './routes/(authed)/manage'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authedManageUsersRouteImport } from './routes/(authed)/manage_/users'
import { Route as authedManageSuppliersRouteImport } from './routes/(authed)/manage_/suppliers'
import { Route as authedManageProductsRouteImport } from './routes/(authed)/manage_/products'
import { Route as authedManageOrdersRouteImport } from './routes/(authed)/manage_/orders'
import { Route as authedManageMaterialsRouteImport } from './routes/(authed)/manage_/materials'
import { Route as authedManageClientsRouteImport } from './routes/(authed)/manage_/clients'
import { Route as authedManageUsersCreateRouteImport } from './routes/(authed)/manage_/users_/create'
import { Route as authedManageSuppliersCreateRouteImport } from './routes/(authed)/manage_/suppliers_/create'
import { Route as authedManageProductsCreateRouteImport } from './routes/(authed)/manage_/products_/create'
import { Route as authedManageProductsProductIdRouteImport } from './routes/(authed)/manage_/products_/$productId'
import { Route as authedManageMaterialsCreateRouteImport } from './routes/(authed)/manage_/materials_/create'
import { Route as authedManageClientsCreateRouteImport } from './routes/(authed)/manage_/clients_/create'
import { Route as authedManageUsersUserIdEditRouteImport } from './routes/(authed)/manage_/users_/$userId.edit'
import { Route as authedManageSuppliersSupplierIdEditRouteImport } from './routes/(authed)/manage_/suppliers_/$supplierId.edit'
import { Route as authedManageMaterialsMaterialIdEditRouteImport } from './routes/(authed)/manage_/materials_/$materialId.edit'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedManageRoute = authedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => authedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authedManageUsersRoute = authedManageUsersRouteImport.update({
  id: '/manage_/users',
  path: '/manage/users',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageSuppliersRoute = authedManageSuppliersRouteImport.update({
  id: '/manage_/suppliers',
  path: '/manage/suppliers',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageProductsRoute = authedManageProductsRouteImport.update({
  id: '/manage_/products',
  path: '/manage/products',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageOrdersRoute = authedManageOrdersRouteImport.update({
  id: '/manage_/orders',
  path: '/manage/orders',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageMaterialsRoute = authedManageMaterialsRouteImport.update({
  id: '/manage_/materials',
  path: '/manage/materials',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageClientsRoute = authedManageClientsRouteImport.update({
  id: '/manage_/clients',
  path: '/manage/clients',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageUsersCreateRoute = authedManageUsersCreateRouteImport.update({
  id: '/manage_/users_/create',
  path: '/manage/users/create',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedManageSuppliersCreateRoute =
  authedManageSuppliersCreateRouteImport.update({
    id: '/manage_/suppliers_/create',
    path: '/manage/suppliers/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageProductsCreateRoute =
  authedManageProductsCreateRouteImport.update({
    id: '/manage_/products_/create',
    path: '/manage/products/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageProductsProductIdRoute =
  authedManageProductsProductIdRouteImport.update({
    id: '/manage_/products_/$productId',
    path: '/manage/products/$productId',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageMaterialsCreateRoute =
  authedManageMaterialsCreateRouteImport.update({
    id: '/manage_/materials_/create',
    path: '/manage/materials/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageClientsCreateRoute =
  authedManageClientsCreateRouteImport.update({
    id: '/manage_/clients_/create',
    path: '/manage/clients/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageUsersUserIdEditRoute =
  authedManageUsersUserIdEditRouteImport.update({
    id: '/manage_/users_/$userId/edit',
    path: '/manage/users/$userId/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageSuppliersSupplierIdEditRoute =
  authedManageSuppliersSupplierIdEditRouteImport.update({
    id: '/manage_/suppliers_/$supplierId/edit',
    path: '/manage/suppliers/$supplierId/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedManageMaterialsMaterialIdEditRoute =
  authedManageMaterialsMaterialIdEditRouteImport.update({
    id: '/manage_/materials_/$materialId/edit',
    path: '/manage/materials/$materialId/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/manage': typeof authedManageRoute
  '/manage/clients': typeof authedManageClientsRoute
  '/manage/materials': typeof authedManageMaterialsRoute
  '/manage/orders': typeof authedManageOrdersRoute
  '/manage/products': typeof authedManageProductsRoute
  '/manage/suppliers': typeof authedManageSuppliersRoute
  '/manage/users': typeof authedManageUsersRoute
  '/manage/clients/create': typeof authedManageClientsCreateRoute
  '/manage/materials/create': typeof authedManageMaterialsCreateRoute
  '/manage/products/$productId': typeof authedManageProductsProductIdRoute
  '/manage/products/create': typeof authedManageProductsCreateRoute
  '/manage/suppliers/create': typeof authedManageSuppliersCreateRoute
  '/manage/users/create': typeof authedManageUsersCreateRoute
  '/manage/materials/$materialId/edit': typeof authedManageMaterialsMaterialIdEditRoute
  '/manage/suppliers/$supplierId/edit': typeof authedManageSuppliersSupplierIdEditRoute
  '/manage/users/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/manage': typeof authedManageRoute
  '/manage/clients': typeof authedManageClientsRoute
  '/manage/materials': typeof authedManageMaterialsRoute
  '/manage/orders': typeof authedManageOrdersRoute
  '/manage/products': typeof authedManageProductsRoute
  '/manage/suppliers': typeof authedManageSuppliersRoute
  '/manage/users': typeof authedManageUsersRoute
  '/manage/clients/create': typeof authedManageClientsCreateRoute
  '/manage/materials/create': typeof authedManageMaterialsCreateRoute
  '/manage/products/$productId': typeof authedManageProductsProductIdRoute
  '/manage/products/create': typeof authedManageProductsCreateRoute
  '/manage/suppliers/create': typeof authedManageSuppliersCreateRoute
  '/manage/users/create': typeof authedManageUsersCreateRoute
  '/manage/materials/$materialId/edit': typeof authedManageMaterialsMaterialIdEditRoute
  '/manage/suppliers/$supplierId/edit': typeof authedManageSuppliersSupplierIdEditRoute
  '/manage/users/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(authed)/manage': typeof authedManageRoute
  '/(authed)/manage_/clients': typeof authedManageClientsRoute
  '/(authed)/manage_/materials': typeof authedManageMaterialsRoute
  '/(authed)/manage_/orders': typeof authedManageOrdersRoute
  '/(authed)/manage_/products': typeof authedManageProductsRoute
  '/(authed)/manage_/suppliers': typeof authedManageSuppliersRoute
  '/(authed)/manage_/users': typeof authedManageUsersRoute
  '/(authed)/manage_/clients_/create': typeof authedManageClientsCreateRoute
  '/(authed)/manage_/materials_/create': typeof authedManageMaterialsCreateRoute
  '/(authed)/manage_/products_/$productId': typeof authedManageProductsProductIdRoute
  '/(authed)/manage_/products_/create': typeof authedManageProductsCreateRoute
  '/(authed)/manage_/suppliers_/create': typeof authedManageSuppliersCreateRoute
  '/(authed)/manage_/users_/create': typeof authedManageUsersCreateRoute
  '/(authed)/manage_/materials_/$materialId/edit': typeof authedManageMaterialsMaterialIdEditRoute
  '/(authed)/manage_/suppliers_/$supplierId/edit': typeof authedManageSuppliersSupplierIdEditRoute
  '/(authed)/manage_/users_/$userId/edit': typeof authedManageUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage'
    | '/manage/clients'
    | '/manage/materials'
    | '/manage/orders'
    | '/manage/products'
    | '/manage/suppliers'
    | '/manage/users'
    | '/manage/clients/create'
    | '/manage/materials/create'
    | '/manage/products/$productId'
    | '/manage/products/create'
    | '/manage/suppliers/create'
    | '/manage/users/create'
    | '/manage/materials/$materialId/edit'
    | '/manage/suppliers/$supplierId/edit'
    | '/manage/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manage'
    | '/manage/clients'
    | '/manage/materials'
    | '/manage/orders'
    | '/manage/products'
    | '/manage/suppliers'
    | '/manage/users'
    | '/manage/clients/create'
    | '/manage/materials/create'
    | '/manage/products/$productId'
    | '/manage/products/create'
    | '/manage/suppliers/create'
    | '/manage/users/create'
    | '/manage/materials/$materialId/edit'
    | '/manage/suppliers/$supplierId/edit'
    | '/manage/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authed)'
    | '/(auth)/login'
    | '/(authed)/manage'
    | '/(authed)/manage_/clients'
    | '/(authed)/manage_/materials'
    | '/(authed)/manage_/orders'
    | '/(authed)/manage_/products'
    | '/(authed)/manage_/suppliers'
    | '/(authed)/manage_/users'
    | '/(authed)/manage_/clients_/create'
    | '/(authed)/manage_/materials_/create'
    | '/(authed)/manage_/products_/$productId'
    | '/(authed)/manage_/products_/create'
    | '/(authed)/manage_/suppliers_/create'
    | '/(authed)/manage_/users_/create'
    | '/(authed)/manage_/materials_/$materialId/edit'
    | '/(authed)/manage_/suppliers_/$supplierId/edit'
    | '/(authed)/manage_/users_/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/manage': {
      id: '/(authed)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof authedManageRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authed)/manage_/users': {
      id: '/(authed)/manage_/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof authedManageUsersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/suppliers': {
      id: '/(authed)/manage_/suppliers'
      path: '/manage/suppliers'
      fullPath: '/manage/suppliers'
      preLoaderRoute: typeof authedManageSuppliersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/products': {
      id: '/(authed)/manage_/products'
      path: '/manage/products'
      fullPath: '/manage/products'
      preLoaderRoute: typeof authedManageProductsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/orders': {
      id: '/(authed)/manage_/orders'
      path: '/manage/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof authedManageOrdersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/materials': {
      id: '/(authed)/manage_/materials'
      path: '/manage/materials'
      fullPath: '/manage/materials'
      preLoaderRoute: typeof authedManageMaterialsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/clients': {
      id: '/(authed)/manage_/clients'
      path: '/manage/clients'
      fullPath: '/manage/clients'
      preLoaderRoute: typeof authedManageClientsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/users_/create': {
      id: '/(authed)/manage_/users_/create'
      path: '/manage/users/create'
      fullPath: '/manage/users/create'
      preLoaderRoute: typeof authedManageUsersCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/suppliers_/create': {
      id: '/(authed)/manage_/suppliers_/create'
      path: '/manage/suppliers/create'
      fullPath: '/manage/suppliers/create'
      preLoaderRoute: typeof authedManageSuppliersCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/products_/create': {
      id: '/(authed)/manage_/products_/create'
      path: '/manage/products/create'
      fullPath: '/manage/products/create'
      preLoaderRoute: typeof authedManageProductsCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/products_/$productId': {
      id: '/(authed)/manage_/products_/$productId'
      path: '/manage/products/$productId'
      fullPath: '/manage/products/$productId'
      preLoaderRoute: typeof authedManageProductsProductIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/materials_/create': {
      id: '/(authed)/manage_/materials_/create'
      path: '/manage/materials/create'
      fullPath: '/manage/materials/create'
      preLoaderRoute: typeof authedManageMaterialsCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/clients_/create': {
      id: '/(authed)/manage_/clients_/create'
      path: '/manage/clients/create'
      fullPath: '/manage/clients/create'
      preLoaderRoute: typeof authedManageClientsCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/users_/$userId/edit': {
      id: '/(authed)/manage_/users_/$userId/edit'
      path: '/manage/users/$userId/edit'
      fullPath: '/manage/users/$userId/edit'
      preLoaderRoute: typeof authedManageUsersUserIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/suppliers_/$supplierId/edit': {
      id: '/(authed)/manage_/suppliers_/$supplierId/edit'
      path: '/manage/suppliers/$supplierId/edit'
      fullPath: '/manage/suppliers/$supplierId/edit'
      preLoaderRoute: typeof authedManageSuppliersSupplierIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/manage_/materials_/$materialId/edit': {
      id: '/(authed)/manage_/materials_/$materialId/edit'
      path: '/manage/materials/$materialId/edit'
      fullPath: '/manage/materials/$materialId/edit'
      preLoaderRoute: typeof authedManageMaterialsMaterialIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedManageRoute: typeof authedManageRoute
  authedManageClientsRoute: typeof authedManageClientsRoute
  authedManageMaterialsRoute: typeof authedManageMaterialsRoute
  authedManageOrdersRoute: typeof authedManageOrdersRoute
  authedManageProductsRoute: typeof authedManageProductsRoute
  authedManageSuppliersRoute: typeof authedManageSuppliersRoute
  authedManageUsersRoute: typeof authedManageUsersRoute
  authedManageClientsCreateRoute: typeof authedManageClientsCreateRoute
  authedManageMaterialsCreateRoute: typeof authedManageMaterialsCreateRoute
  authedManageProductsProductIdRoute: typeof authedManageProductsProductIdRoute
  authedManageProductsCreateRoute: typeof authedManageProductsCreateRoute
  authedManageSuppliersCreateRoute: typeof authedManageSuppliersCreateRoute
  authedManageUsersCreateRoute: typeof authedManageUsersCreateRoute
  authedManageMaterialsMaterialIdEditRoute: typeof authedManageMaterialsMaterialIdEditRoute
  authedManageSuppliersSupplierIdEditRoute: typeof authedManageSuppliersSupplierIdEditRoute
  authedManageUsersUserIdEditRoute: typeof authedManageUsersUserIdEditRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedManageRoute: authedManageRoute,
  authedManageClientsRoute: authedManageClientsRoute,
  authedManageMaterialsRoute: authedManageMaterialsRoute,
  authedManageOrdersRoute: authedManageOrdersRoute,
  authedManageProductsRoute: authedManageProductsRoute,
  authedManageSuppliersRoute: authedManageSuppliersRoute,
  authedManageUsersRoute: authedManageUsersRoute,
  authedManageClientsCreateRoute: authedManageClientsCreateRoute,
  authedManageMaterialsCreateRoute: authedManageMaterialsCreateRoute,
  authedManageProductsProductIdRoute: authedManageProductsProductIdRoute,
  authedManageProductsCreateRoute: authedManageProductsCreateRoute,
  authedManageSuppliersCreateRoute: authedManageSuppliersCreateRoute,
  authedManageUsersCreateRoute: authedManageUsersCreateRoute,
  authedManageMaterialsMaterialIdEditRoute:
    authedManageMaterialsMaterialIdEditRoute,
  authedManageSuppliersSupplierIdEditRoute:
    authedManageSuppliersSupplierIdEditRoute,
  authedManageUsersUserIdEditRoute: authedManageUsersUserIdEditRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
